### ISSUE TITLE
Encouraging use of TailwindCSS development build in production?

### ISSUE THREAD

**Issue by danawoodman** [thedevdojo/pines#18]
Am I correct in assuming Pines is encouraging people to use Tailwind with the dev JS build?

The [docs here](https://devdojo.com/pines/docs/how-to-use) state to use it and I see no docs on a production version of this.

![image](https://github.com/thedevdojo/pines/assets/157695/4e95bdb0-ab3f-466b-a802-33de74b7439f)

**Comment by tnylea** [comment]
Nope. We are not encouraging the use of TailwindCDN in production. If there's somewhere on the site that you think we can make this more clear let me know. I've added a warning with the following message: https://github.com/thedevdojo/pines/blob/main/getting-started/how-to-use.html#L8 to that page.

On that page it does state: `If you want to test an element on a single HTML page, you can copy/paste this snippet below into any `.html` file:`

But just in case that wasn't clear I've added a warning on that page about using in production. That warning should go live on the site the next time we deploy on DevDojo.

Thanks!

**Comment by danawoodman** [comment]
Glad to hear 👍 I think the warning will help people
