### ISSUE TITLE
Toasts don't seem to work outside of docs page

### ISSUE THREAD

**Issue by ikelkar** [thedevdojo/pines#35]
While the toast seems to work nicely on this page: https://devdojo.com/pines/docs/toast, the playground doesn't seem to work nor does copying the component code

**Comment by pixelastronauts** [comment]
Make sure you have a x-data surrounding both the toast component & the buttons. This is indeed missing in the example code, so copying that code doesn't work out of the box.

```
<div class="relative w-auto h-auto" x-data>
    // Implementation of all buttons & toasts
</div>
```

**Comment by jp319** [comment]
The toast doesn't work when used outside the docs.

It also doesn't work in the playground, its only showing a single line, see screenshot below:

![Screenshot from 2024-11-30 13-00-51](https://github.com/user-attachments/assets/7fd1a658-4cc7-4f1a-b644-0446089e569a)
