### ISSUE TITLE
License

### ISSUE THREAD

**Issue by afonic** [thedevdojo/pines#6]
Hello guys! Congratulations on your work, it will really help build up the AlpineJS ecosystem as something like this is really missing!

I've failed to find the license for this code, which is critical if people are going to use this code in their projects, is this something you plan to add?

**Comment by srcreigh** [comment]
+1 will try this once the license is sorted (watching the thread)

**Comment by lloyd-mcgarrigal** [comment]
I hate to leave a "this" style comment but this is kind of a big deal. I won't even tell people about this (or anything) without a license.

**Comment by ocharles** [comment]
https://github.com/thedevdojo/pines/commit/ae16d338827e8a5a759722c72b704697c34c7be2 There should probably be a `LICENSE` file, but it looks like pines is MIT licensed.

**Comment by tnylea** [comment]
Just added the license a few weeks ago. Closing this issue.

Thanks guys 😊
